export const GET_YHTEYSTIEDOT = "GET_YHTEYSTIEDOT";
export const GET_YHTEYSTIETO = "GET_YHTEYSTIETO";
export const DELETE_YHTEYSTIETO = "DELETE_YHTEYSTIETO";
export const ADD_YHTEYSTIETO = "ADD_YHTEYSTIETO";
